wip

diff --git a/.github/workflows/ci-linux.yml b/.github/workflows/ci-linux.yml
--- a/.github/workflows/ci-linux.yml
+++ b/.github/workflows/ci-linux.yml
@@ -28,33 +28,33 @@ jobs:
         uses: ikalnytskyi/action-setup-postgres@v3
         id: pg
 
-      - run: |
-          # postgresql://postgres:postgres@localhost:5432/postgres
-          echo "CONNECTION_URI = $CONNECTION_URI" | base64
-          # start postgresql
-          brew services start postgresql
-          psql -v ON_ERROR_STOP=1 -c "select version();" "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c "SELECT current_user;" "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c "SELECT session_user;" "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c "RESET ROLE;" "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c "SELECT * FROM pg_roles;" "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c '\l' "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c '\l+' "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c 'show is_superuser;' "$CONNECTION_URI"
-
-          dropuser -e postgres || echo "dropuser1 custom failed"
-          PGPASSWORD=postgres dropuser -e -h localhost -U postgres postgres || echo "dropuser custom failed"
-
-          pg_ctl -D /usr/local/var/postgres start || echo "pg_ctl failed"
-          createuser -s postgres || echo "createuser failed"
-          PGPASSWORD=postgres createuser -e -h localhost -U postgres -s postgres || echo "ceateuser2 custom failed"
-
-          # sudo -i -u postgres psql -v ON_ERROR_STOP=1 -c 'show is_superuser;' "$CONNECTION_URI"
-
-          # psql -v ON_ERROR_STOP=1 -c "CREATE EXTENSION postgis;" "$CONNECTION_URI"
-
-        env:
-          CONNECTION_URI: ${{ steps.pg.outputs.connection-uri }}
+#      - run: |
+#          # postgresql://postgres:postgres@localhost:5432/postgres
+#          echo "CONNECTION_URI = $CONNECTION_URI" | base64
+#          # start postgresql
+#          brew services start postgresql
+#          psql -v ON_ERROR_STOP=1 -c "select version();" "$CONNECTION_URI"
+#          psql -v ON_ERROR_STOP=1 -c "SELECT current_user;" "$CONNECTION_URI"
+#          psql -v ON_ERROR_STOP=1 -c "SELECT session_user;" "$CONNECTION_URI"
+#          psql -v ON_ERROR_STOP=1 -c "RESET ROLE;" "$CONNECTION_URI"
+#          psql -v ON_ERROR_STOP=1 -c "SELECT * FROM pg_roles;" "$CONNECTION_URI"
+#          psql -v ON_ERROR_STOP=1 -c '\l' "$CONNECTION_URI"
+#          psql -v ON_ERROR_STOP=1 -c '\l+' "$CONNECTION_URI"
+#          psql -v ON_ERROR_STOP=1 -c 'show is_superuser;' "$CONNECTION_URI"
+#
+#          dropuser -e postgres || echo "1dropuser1 custom failed"
+#          PGPASSWORD=postgres dropuser -e -h localhost -U postgres postgres || echo "1dropuser custom failed"
+#
+#          pg_ctl -D /usr/local/var/postgres start || echo "1pg_ctl failed"
+#          createuser -s postgres || echo "1createuser failed"
+#          PGPASSWORD=postgres createuser -e -h localhost -U postgres -s postgres || echo "1ceateuser2 custom failed"
+#
+#          # sudo -i -u postgres psql -v ON_ERROR_STOP=1 -c 'show is_superuser;' "$CONNECTION_URI"
+#
+#          # psql -v ON_ERROR_STOP=1 -c "CREATE EXTENSION postgis;" "$CONNECTION_URI"
+#
+#        env:
+#          CONNECTION_URI: ${{ steps.pg.outputs.connection-uri }}
 
       - run: |
           brew install postgis
@@ -67,33 +67,35 @@ jobs:
         env:
           CONNECTION_URI: ${{ steps.pg.outputs.connection-uri }}
         run: |
-          echo "CONNECTION_URI = $CONNECTION_URI" | base64
-          set -x
+          echo "Recreating postgres user as a superuser"
+          dropuser -e postgres
+          createuser -s postgres
+          psql -v ON_ERROR_STOP=1 -c "CREATE EXTENSION postgis;" "$CONNECTION_URI"
+
+          
+          # echo "CONNECTION_URI = $CONNECTION_URI" | base64
+          # set -x
           # which pg_ctl || true
           # which pg_isready || true
           # which psql || true
           # export | sort
           # sudo systemctl start postgresql.service
           # pg_isready
-          psql -v ON_ERROR_STOP=1 -c "select version();" "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c "SELECT current_user;" "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c "SELECT session_user;" "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c "RESET ROLE;" "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c "SELECT * FROM pg_roles;" "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c '\l' "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c '\l+' "$CONNECTION_URI"
-          psql -v ON_ERROR_STOP=1 -c 'show is_superuser;' "$CONNECTION_URI"
-
-          dropuser -e postgres || echo "dropuser1 custom failed"
-          PGPASSWORD=postgres dropuser -e -h localhost -U postgres postgres || echo "dropuser custom failed"
-
-          pg_ctl -D /usr/local/var/postgres start || echo "pg_ctl failed"
-          createuser -s postgres || echo "createuser failed"
-
+          # psql -v ON_ERROR_STOP=1 -c "select version();" "$CONNECTION_URI"
+          # psql -v ON_ERROR_STOP=1 -c "SELECT current_user;" "$CONNECTION_URI"
+          # psql -v ON_ERROR_STOP=1 -c "SELECT session_user;" "$CONNECTION_URI"
+          # psql -v ON_ERROR_STOP=1 -c "RESET ROLE;" "$CONNECTION_URI"
+          # psql -v ON_ERROR_STOP=1 -c "SELECT * FROM pg_roles;" "$CONNECTION_URI"
+          # psql -v ON_ERROR_STOP=1 -c '\l' "$CONNECTION_URI"
+          # psql -v ON_ERROR_STOP=1 -c '\l+' "$CONNECTION_URI"
+          # psql -v ON_ERROR_STOP=1 -c 'show is_superuser;' "$CONNECTION_URI"
+          # PGPASSWORD=postgres dropuser -e -h localhost -U postgres postgres || echo "2dropuser custom failed"
+          # pg_ctl -D /usr/local/var/postgres start || echo "2pg_ctl failed"
           # sudo -i -u postgres psql -v ON_ERROR_STOP=1 -c 'show is_superuser;' "$CONNECTION_URI"
 
-          psql -v ON_ERROR_STOP=1 -c "CREATE EXTENSION postgis;" "$CONNECTION_URI"
 
+#  postgreService=$(brew services list | grep -oe "postgresql\S*")
+#  brew services start $postgreService
 
 #      - name: Decide Postgis version
 #        # Download the list of available Postgis versions, and decide which one to use
